version: '3'
services:
  db:
    image: postgres:12.0
  redis:
    image: redis:5.0
    restart: always
    ports:
       - "6379"
  worker:
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    build: ./worker
  poll:
    depends_on:
      - redis
    build: ./poll
    ports:
      - "5000:80"
    links:
      - redis
  result:
      depends_on:
        - db
      links:
        - db
      build: ./result
      ports:
         - "5001:4242"
volumes:
  db-data: {}
