version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD : password
      POSTGRES_USER : postgres
      HOST_HOSTNAME : db
    volumes:
        - ./shema.sql:/docker-entrypoint-initdb.d/shema.sql
    networks:
        - result-tier
        - back-tier
  redis:
    image: redis:5.0
    restart: always
    ports:
       - "6379"
    environment:
      HOST_HOSTNAME : redis
    networks:
        - back-tier
        - poll-tier
  worker:
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    build: ./worker
    environment:
      HOST_HOSTNAME : worker
    networks:
        - back-tier
  poll:
    depends_on:
      - redis
    build: ./poll
    ports:
      - "5000:80"
    links:
      - redis
    environment:
      HOST_HOSTNAME : poll
    networks:
        - poll-tier
  result:
      depends_on:
        - db
      links:
        - db
      build: ./result
      ports:
         - "5001:80"
      environment:
        HOST_HOSTNAME : result
      networks:
        - result-tier
networks:
    poll-tier:
    result-tier:
    back-tier:
volumes:
  db-data: {}
