version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD : password
      POSTGRES_USER : postgres
      HOST_HOSTNAME : db
  redis:
    image: redis:5.0
    restart: always
    ports:
       - "6379"
    environment:
      HOST_HOSTNAME : redis
  worker:
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    build: ./worker
    environment:
      HOST_HOSTNAME : worker
  poll:
    depends_on:
      - redis
    build: ./poll
    ports:
      - "5000:80"
    links:
      - redis
    environment:
      HOST_HOSTNAME : poll
  result:
      depends_on:
        - db
      links:
        - db
      build: ./result
      ports:
         - "5001:4242"
      environment:
        HOST_HOSTNAME : result
volumes:
  db-data: {}
